package frc.lib.catalyst.physics.sim;

import java.util.Random;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveModuleState;

import frc.lib.catalyst.physics.PhysicsSample;
import frc.lib.catalyst.physics.model.DrivetrainModel;
import frc.lib.catalyst.physics.model.RobotModel;

/**
 * A robot that knows the truth, so Physics Core can be marked against it.
 *
 * <p>Physics Core is an estimator, and the only way to know whether an estimator is any good is to
 * compare it against a state you already know. A real robot never gives you that — the whole reason
 * the estimator exists is that nobody knows the true velocity. A simulation does.
 *
 * <p>This carries a true pose and velocity, applies traction-limited dynamics to them, and then
 * produces the {@link PhysicsSample} a real robot's sensors <em>would</em> have reported. Feed that
 * sample to {@link frc.lib.catalyst.physics.PhysicsCore} and compare its answers to
 * {@link #trueFieldVelocity()}.
 *
 * <h2>Why this is not circular</h2>
 * A simulator built from the same model as the estimator proves nothing: of course the estimator
 * recovers a truth that was generated by its own assumptions. So this deliberately does things
 * Physics Core does not model, and the validation is only meaningful because of them:
 *
 * <ul>
 *   <li><b>Wheel radius error</b> — the sim's wheels are a configurable percentage off what the code
 *       believes, so encoder speeds are systematically wrong the way a real robot's are.</li>
 *   <li><b>Accelerometer bias and noise</b> — a constant offset plus per-sample noise, neither of
 *       which the estimator knows about.</li>
 *   <li><b>Module speed noise</b> — encoders are not exact.</li>
 *   <li><b>Odometry drift</b> — the reported pose integrates <em>wheel</em> speed, so a slip event
 *       permanently displaces it, exactly as a real drivetrain estimator's pose does.</li>
 *   <li><b>Slip that outlasts the command</b> — wheels keep over-reporting for a moment after grip
 *       returns, rather than snapping back.</li>
 * </ul>
 *
 * <pre>{@code
 * SimulatedRobot sim = SimulatedRobot.builder()
 *     .robotModel(model).kinematics(kinematics)
 *     .wheelRadiusError(1.03)                 // sim wheels 3% larger than the code thinks
 *     .accelerometerBias(new Translation2d(0.05, -0.02))
 *     .seed(42)
 *     .build();
 *
 * sim.command(new ChassisSpeeds(3.0, 0, 0));
 * for (int i = 0; i < 100; i++) {
 *     sim.step();
 *     physics.update(sim.sample());
 *     double error = physics.state().speedMetersPerSecond() - sim.trueSpeed();
 * }
 * }</pre>
 *
 * <p>Deterministic: the noise comes from a seeded {@link Random}, so the same seed replays the same
 * run exactly. That is what lets a validation scenario be a unit test rather than a flaky one.
 *
 * <p><b>What sim validation can and cannot show.</b> It can show that the estimator recovers a known
 * truth from imperfect sensors — that the fusion, the slip scoring, and the detectors work as
 * designed. It cannot show that the <em>model</em> matches carpet: real friction is not a constant,
 * real bumpers are not rigid, and real modules do not all break loose at once. That is what shadow
 * mode on a real robot is for, and why the RFC's validation ladder puts simulation before it rather
 * than instead of it.
 *
 * @since 1.7.0
 */
public final class SimulatedRobot {

    private final RobotModel robotModel;
    private final DrivetrainModel drivetrain;
    private final SwerveDriveKinematics kinematics;
    private final int moduleCount;
    private final double dt;

    private final double wheelRadiusError;
    private final Translation2d accelerometerBias;
    private final double accelerometerNoise;
    private final double moduleSpeedNoise;
    private final double gyroNoise;
    private final double velocityTimeConstant;
    private final double wheelRecoverySeconds;
    private final Random random;

    /** Ground truth. */
    private Pose2d truePose = Pose2d.kZero;
    private Translation2d trueVelocity = Translation2d.kZero;
    private Translation2d trueAcceleration = Translation2d.kZero;
    private double trueOmega = 0.0;

    /** What the wheels believe, which diverges from the truth whenever they slip. */
    private Translation2d wheelVelocity = Translation2d.kZero;
    /** The pose a drivetrain estimator would report, integrated from wheel velocity. */
    private Pose2d odometryPose = Pose2d.kZero;

    private ChassisSpeeds commandedRobotRelative = new ChassisSpeeds();
    private Translation2d externalAcceleration = Translation2d.kZero;
    /** Per-module over-reporting, for the differential slip a uniform model cannot produce. */
    private final double[] moduleSlipBias;
    private double frictionScale = 1.0;
    private double timestamp = 0.0;
    private boolean slipping = false;
    private double slipUntil = Double.NEGATIVE_INFINITY;

    private SimulatedRobot(Builder builder) {
        this.robotModel = builder.robotModel;
        this.drivetrain = new DrivetrainModel(builder.robotModel);
        this.kinematics = builder.kinematics;
        this.moduleCount = builder.moduleCount;
        this.dt = builder.loopPeriod;
        this.wheelRadiusError = builder.wheelRadiusError;
        this.accelerometerBias = builder.accelerometerBias;
        this.accelerometerNoise = builder.accelerometerNoise;
        this.moduleSpeedNoise = builder.moduleSpeedNoise;
        this.gyroNoise = builder.gyroNoise;
        this.velocityTimeConstant = builder.velocityTimeConstant;
        this.wheelRecoverySeconds = builder.wheelRecoverySeconds;
        this.random = new Random(builder.seed);
        this.moduleSlipBias = new double[builder.moduleCount];
    }

    // ===========================================
    //                  DRIVING
    // ===========================================

    /** Ask the robot to travel at these robot-relative speeds. It gets there as fast as grip allows. */
    public void command(ChassisSpeeds robotRelative) {
        this.commandedRobotRelative = robotRelative == null ? new ChassisSpeeds() : robotRelative;
    }

    /** Ask the robot to stop. */
    public void stop() {
        command(new ChassisSpeeds());
    }

    /**
     * Apply an outside push for this step only — a defender, a wall, a game piece. Cleared after the
     * next {@link #step()}, so a sustained impact means calling it each loop.
     *
     * @param fieldAcceleration acceleration the drivetrain did not command, m/s^2
     */
    public void applyExternalAcceleration(Translation2d fieldAcceleration) {
        this.externalAcceleration = fieldAcceleration == null ? Translation2d.kZero : fieldAcceleration;
    }

    /**
     * Scale the available grip, to simulate a slick patch of carpet or a puddle of coolant.
     * {@code 1.0} is the model's coefficient of friction; {@code 0.3} is ice.
     *
     * <p>Grip loss here is <b>uniform</b>: every wheel breaks loose together, so forward kinematics
     * over-reports in exactly the same way every module does and no per-module residual appears. That
     * is the real blind spot in per-module slip scoring, and it is why validating it needs
     * {@link #setModuleSlipBias(int, double)} as well.
     */
    public void setFrictionScale(double frictionScale) {
        this.frictionScale = Math.max(0.0, frictionScale);
    }

    /**
     * Make one module over-report, independently of the others — a single wheel on a slick patch, or
     * one lifted off the carpet by a bump.
     *
     * <p>This is the <b>differential</b> slip that per-module residuals exist to catch, as opposed to
     * the uniform loss of grip {@link #setFrictionScale(double)} produces. Both happen on real
     * robots, they are detected by different parts of Physics Core, and a validation run that only
     * exercised one of them would leave half the story untested.
     *
     * @param moduleIndex   which module, in kinematics order
     * @param extraSpeedMps how much faster it reads than it should, in m/s. Zero clears it
     */
    public void setModuleSlipBias(int moduleIndex, double extraSpeedMps) {
        if (moduleIndex < 0 || moduleIndex >= moduleSlipBias.length) {
            throw new IllegalArgumentException("moduleIndex must be in [0, " + moduleSlipBias.length
                    + ") (got " + moduleIndex + ")");
        }
        moduleSlipBias[moduleIndex] = extraSpeedMps;
    }

    /** Clear every per-module bias. */
    public void clearModuleSlipBias() {
        java.util.Arrays.fill(moduleSlipBias, 0.0);
    }

    /** True while any module is biased — the ground truth for differential slip detection. */
    public boolean hasModuleSlip() {
        for (double bias : moduleSlipBias) {
            if (bias != 0.0) return true;
        }
        return false;
    }

    /**
     * Advance one loop.
     *
     * <p>The controller asks for whatever acceleration would reach the commanded velocity within the
     * configured time constant. If that exceeds what the carpet can transmit, the robot gets the
     * traction limit and the wheels get what was asked for — which is what slip <em>is</em>, and why
     * the encoders over-report through it.
     */
    public void step() {
        Rotation2d heading = truePose.getRotation();
        ChassisSpeeds commandedField =
                ChassisSpeeds.fromRobotRelativeSpeeds(commandedRobotRelative, heading);
        Translation2d targetVelocity =
                new Translation2d(commandedField.vxMetersPerSecond, commandedField.vyMetersPerSecond);

        Translation2d desiredAcceleration = targetVelocity.minus(trueVelocity).div(velocityTimeConstant);
        double tractionLimit = drivetrain.maxTractionAccelerationMpsSq() * frictionScale;
        double desiredMagnitude = desiredAcceleration.getNorm();

        Translation2d appliedAcceleration = desiredAcceleration;
        slipping = false;
        if (desiredMagnitude > tractionLimit && desiredMagnitude > 1e-9) {
            appliedAcceleration = desiredAcceleration.times(tractionLimit / desiredMagnitude);
            slipping = true;
            slipUntil = timestamp + wheelRecoverySeconds;
        }

        // The external push is not limited by traction: it is something else doing the pushing.
        boolean beingPushed = externalAcceleration.getNorm() > 1e-9;
        trueAcceleration = appliedAcceleration.plus(externalAcceleration);
        trueVelocity = trueVelocity.plus(trueAcceleration.times(dt));

        // What the encoders see is wheel rotation, which is not the same as how the robot is moving.
        if (slipping) {
            // Spinning: the wheels turn at the rate the controller asked for, not the rate the carpet
            // allows.
            wheelVelocity = wheelVelocity.plus(desiredAcceleration.times(dt));
        } else if (beingPushed) {
            // Being shoved: a swerve wheel measures rolling along its own axis, so it skids through a
            // sideways hit and the encoders never see it. The wheels keep reporting the drivetrain's
            // own contribution only - which is precisely why an impact is visible as acceleration the
            // wheels cannot account for.
            wheelVelocity = wheelVelocity.plus(appliedAcceleration.times(dt));
        } else {
            // Rolling cleanly: the wheels re-sync with the real ground speed over a few loops, rather
            // than snapping to it, because a spun-up or skidded wheel takes a moment to settle.
            wheelVelocity = wheelVelocity.plus(trueVelocity.minus(wheelVelocity)
                    .times(timestamp < slipUntil ? 0.35 : 0.6));
        }

        trueOmega = commandedField.omegaRadiansPerSecond;
        double heading2 = heading.getRadians() + trueOmega * dt;

        truePose = new Pose2d(truePose.getTranslation().plus(trueVelocity.times(dt)),
                new Rotation2d(heading2));
        // Odometry integrates the wheels, so a slip displaces it permanently - exactly like a real
        // drivetrain pose estimator with no absolute correction.
        odometryPose = new Pose2d(odometryPose.getTranslation().plus(wheelVelocity.times(dt)),
                new Rotation2d(heading2));

        externalAcceleration = Translation2d.kZero;
        timestamp += dt;
    }

    /** Advance {@code loops} steps with the current command. */
    public void step(int loops) {
        for (int i = 0; i < loops; i++) step();
    }

    // ===========================================
    //              WHAT THE ROBOT SEES
    // ===========================================

    /**
     * The measurements a real robot's sensors would have produced this loop — wheel-derived speeds
     * scaled by the radius error, module states with encoder noise, a biased and noisy accelerometer,
     * and the drifted odometry pose.
     */
    public PhysicsSample sample() {
        Rotation2d heading = odometryPose.getRotation();
        // Encoders measure wheel rotations and the code multiplies by the radius it was told. Get
        // that radius wrong and every speed is wrong by the same factor.
        Translation2d reported = wheelVelocity.times(wheelRadiusError);
        ChassisSpeeds robotRelative = ChassisSpeeds.fromFieldRelativeSpeeds(
                reported.getX(), reported.getY(), trueOmega + noise(gyroNoise), heading);

        SwerveModuleState[] states = kinematics.toSwerveModuleStates(robotRelative);
        if (states.length > moduleCount) {
            SwerveModuleState[] trimmed = new SwerveModuleState[moduleCount];
            System.arraycopy(states, 0, trimmed, 0, moduleCount);
            states = trimmed;
        }
        for (int i = 0; i < states.length; i++) {
            states[i] = new SwerveModuleState(
                    states[i].speedMetersPerSecond + moduleSlipBias[i] + noise(moduleSpeedNoise),
                    states[i].angle);
        }

        Translation2d measuredAcceleration = trueAcceleration
                .rotateBy(truePose.getRotation().unaryMinus())
                .plus(accelerometerBias)
                .plus(new Translation2d(noise(accelerometerNoise), noise(accelerometerNoise)));

        return new PhysicsSample(timestamp, odometryPose, robotRelative, states,
                measuredAcceleration, robotRelative.omegaRadiansPerSecond);
    }

    /** The pose a drivetrain estimator would be reporting — drifted by any slip that has happened. */
    public Pose2d odometryPose() {
        return odometryPose;
    }

    /** Correct the odometry pose to the truth, as an accepted vision measurement would. */
    public void applyPerfectVisionCorrection() {
        odometryPose = truePose;
    }

    // ===========================================
    //                 THE TRUTH
    // ===========================================

    /** Where the robot really is. */
    public Pose2d truePose() {
        return truePose;
    }

    /** How fast it really is going, field-relative. */
    public ChassisSpeeds trueFieldVelocity() {
        return new ChassisSpeeds(trueVelocity.getX(), trueVelocity.getY(), trueOmega);
    }

    /** Ground speed, m/s. */
    public double trueSpeed() {
        return trueVelocity.getNorm();
    }

    /** True field-relative acceleration, m/s^2. */
    public Translation2d trueAcceleration() {
        return trueAcceleration;
    }

    /** True velocity as a vector, m/s. */
    public Translation2d trueVelocityVector() {
        return trueVelocity;
    }

    /** What the wheels currently believe the velocity is — the encoder-only estimate to beat. */
    public Translation2d wheelVelocity() {
        return wheelVelocity.times(wheelRadiusError);
    }

    /** True this loop if the drivetrain exceeded available grip. The ground truth for slip detection. */
    public boolean isSlipping() {
        return slipping;
    }

    /** How far the odometry pose has drifted from the truth, in metres. */
    public double odometryErrorMeters() {
        return odometryPose.getTranslation().getDistance(truePose.getTranslation());
    }

    /** Simulated time, in seconds. */
    public double timestamp() {
        return timestamp;
    }

    /** The physical model this simulation obeys. */
    public RobotModel robotModel() {
        return robotModel;
    }

    /** Put everything back to the origin, at rest, at time zero. */
    public void reset() {
        truePose = Pose2d.kZero;
        odometryPose = Pose2d.kZero;
        trueVelocity = Translation2d.kZero;
        wheelVelocity = Translation2d.kZero;
        trueAcceleration = Translation2d.kZero;
        trueOmega = 0.0;
        timestamp = 0.0;
        slipping = false;
        slipUntil = Double.NEGATIVE_INFINITY;
        frictionScale = 1.0;
        externalAcceleration = Translation2d.kZero;
        commandedRobotRelative = new ChassisSpeeds();
        clearModuleSlipBias();
    }

    /** Zero-mean noise with the given standard deviation. Zero when noise is disabled. */
    private double noise(double standardDeviation) {
        return standardDeviation <= 0 ? 0.0 : random.nextGaussian() * standardDeviation;
    }

    /** Start building a simulated robot. */
    public static Builder builder() {
        return new Builder();
    }

    /** Builder for {@link SimulatedRobot}. */
    public static final class Builder {
        private RobotModel robotModel;
        private SwerveDriveKinematics kinematics;
        private int moduleCount = 4;
        private double loopPeriod = 0.02;
        private double wheelRadiusError = 1.0;
        private Translation2d accelerometerBias = Translation2d.kZero;
        private double accelerometerNoise = 0.0;
        private double moduleSpeedNoise = 0.0;
        private double gyroNoise = 0.0;
        private double velocityTimeConstant = 0.25;
        private double wheelRecoverySeconds = 0.15;
        private long seed = 20260805L;

        /** The physical model the simulation obeys. Required. */
        public Builder robotModel(RobotModel robotModel) {
            this.robotModel = robotModel;
            return this;
        }

        /** The drivetrain's kinematics, used to synthesise module states. Required. */
        public Builder kinematics(SwerveDriveKinematics kinematics, int moduleCount) {
            this.kinematics = kinematics;
            this.moduleCount = moduleCount;
            return this;
        }

        /** Four-module convenience for {@link #kinematics(SwerveDriveKinematics, int)}. */
        public Builder kinematics(SwerveDriveKinematics kinematics) {
            return kinematics(kinematics, 4);
        }

        /** Simulated loop period in seconds. Defaults to 0.02. */
        public Builder loopPeriod(double loopPeriod) {
            this.loopPeriod = loopPeriod;
            return this;
        }

        /**
         * Ratio between the simulation's real wheel radius and the one the robot code assumes.
         * {@code 1.03} means the wheels are 3% larger than the constants file says, so every encoder
         * speed reads 3% high. Defaults to 1.0 (perfect). This is the error
         * {@code WheelRadiusCalibration} exists to find, and the one Physics Core's sensor-disagreement
         * residual should surface.
         */
        public Builder wheelRadiusError(double wheelRadiusError) {
            this.wheelRadiusError = wheelRadiusError;
            return this;
        }

        /** Constant accelerometer offset, robot-relative, m/s^2. Defaults to none. */
        public Builder accelerometerBias(Translation2d accelerometerBias) {
            this.accelerometerBias = accelerometerBias;
            return this;
        }

        /** Per-sample accelerometer noise, 1-sigma, m/s^2. Defaults to none. */
        public Builder accelerometerNoise(double accelerometerNoise) {
            this.accelerometerNoise = accelerometerNoise;
            return this;
        }

        /** Per-sample module speed noise, 1-sigma, m/s. Defaults to none. */
        public Builder moduleSpeedNoise(double moduleSpeedNoise) {
            this.moduleSpeedNoise = moduleSpeedNoise;
            return this;
        }

        /** Per-sample gyro rate noise, 1-sigma, rad/s. Defaults to none. */
        public Builder gyroNoise(double gyroNoise) {
            this.gyroNoise = gyroNoise;
            return this;
        }

        /**
         * How quickly the drivetrain controller tries to reach a commanded velocity, in seconds.
         * Smaller means a more aggressive controller, which slips more readily. Defaults to 0.25.
         */
        public Builder velocityTimeConstant(double velocityTimeConstant) {
            this.velocityTimeConstant = velocityTimeConstant;
            return this;
        }

        /**
         * How long the wheels keep over-reporting after grip returns, in seconds. Defaults to 0.15 —
         * a spun-up wheel does not snap back to the chassis speed the instant it bites.
         */
        public Builder wheelRecoverySeconds(double wheelRecoverySeconds) {
            this.wheelRecoverySeconds = wheelRecoverySeconds;
            return this;
        }

        /** Seed for the noise generator. Same seed, same run, every time. Defaults to a fixed value. */
        public Builder seed(long seed) {
            this.seed = seed;
            return this;
        }

        /**
         * A realistic sensor suite: 3% wheel radius error, a small accelerometer bias, and noise on
         * every channel. This is the configuration a validation run should use, because a simulation
         * with perfect sensors proves considerably less.
         */
        public Builder withRealisticSensors() {
            return wheelRadiusError(1.03)
                    .accelerometerBias(new Translation2d(0.08, -0.05))
                    .accelerometerNoise(0.25)
                    .moduleSpeedNoise(0.015)
                    .gyroNoise(0.004);
        }

        /** Validate and build. */
        public SimulatedRobot build() {
            if (robotModel == null) {
                throw new IllegalStateException("a RobotModel is required - the simulation's traction "
                        + "limit comes from it");
            }
            if (kinematics == null) {
                throw new IllegalStateException("kinematics is required - module states are synthesised "
                        + "from it");
            }
            if (!(loopPeriod > 0)) {
                throw new IllegalStateException("loopPeriod must be > 0 (got " + loopPeriod + ")");
            }
            if (!(velocityTimeConstant > 0)) {
                throw new IllegalStateException("velocityTimeConstant must be > 0 (got "
                        + velocityTimeConstant + ")");
            }
            if (!(wheelRadiusError > 0)) {
                throw new IllegalStateException("wheelRadiusError must be > 0 (got "
                        + wheelRadiusError + ")");
            }
            return new SimulatedRobot(this);
        }
    }
}
